var fname = [
"./img/index/0.JPG",
"./img/index/1.JPG",
"./img/index/10.JPG",
"./img/index/11.JPG",
"./img/index/12.JPG",
"./img/index/13.JPG",
"./img/index/15.JPG",
"./img/index/16.JPG",
"./img/index/18.JPG",
"./img/index/19.png",
"./img/index/3.JPG",
"./img/index/7.JPG",
"./img/index/8.JPG",
"./img/index/9.JPG",
"./img/index/DSC03531.JPG",
"./img/index/LRG_DSC03913.JPG",
];
